import 'package:uuid/uuid.dart';

/// ═══════════════════════════════════════════════════════════════
/// MemoryBlock Architecture
///
/// Antheia is no longer a simple string "body" text field.
/// A journal entry is a linear stack of 'Blocks'.
/// This allows us to naturally interleave text, voice transcriptions,
/// images, and reflections without breaking the flow.
/// ═══════════════════════════════════════════════════════════════

enum BlockType { text, voice, image, reflection }

abstract class MemoryBlock {
  final String id;
  final BlockType type;

  MemoryBlock({String? id, required this.type}) : id = id ?? const Uuid().v4();

  // For serialization
  Map<String, dynamic> toJson();
}

/// Standard text block typed by the user.
class TextBlock extends MemoryBlock {
  String text;

  TextBlock({String? id, this.text = ''}) : super(id: id, type: BlockType.text);

  @override
  Map<String, dynamic> toJson() => {
        'id': id,
        'type': 'text',
        'text': text,
      };

  factory TextBlock.fromJson(Map<String, dynamic> json) {
    return TextBlock(
      id: json['id'],
      text: json['text'] ?? '',
    );
  }
}

/// A block generated from a voice recording. Contains both the transcript
/// and a reference to the audio file for playback/waveform generation.
class VoiceBlock extends MemoryBlock {
  String transcript;
  String? audioPath;
  Duration? duration;

  VoiceBlock({
    String? id,
    this.transcript = '',
    this.audioPath,
    this.duration,
  }) : super(id: id, type: BlockType.voice);

  @override
  Map<String, dynamic> toJson() => {
        'id': id,
        'type': 'voice',
        'transcript': transcript,
        'audioPath': audioPath,
        'duration': duration?.inMilliseconds,
      };

  factory VoiceBlock.fromJson(Map<String, dynamic> json) {
    return VoiceBlock(
      id: json['id'],
      transcript: json['transcript'] ?? '',
      audioPath: json['audioPath'],
      duration: json['duration'] != null ? Duration(milliseconds: json['duration']) : null,
    );
  }
}

/// A quiet observation or reflection generated by the ambient reflection.
class ReflectionBlock extends MemoryBlock {
  String content;
  bool isRead;

  ReflectionBlock({
    String? id,
    required this.content,
    this.isRead = false,
  }) : super(id: id, type: BlockType.reflection);

  @override
  Map<String, dynamic> toJson() => {
        'id': id,
        'type': 'reflection',
        'content': content,
        'isRead': isRead,
      };

  factory ReflectionBlock.fromJson(Map<String, dynamic> json) {
    return ReflectionBlock(
      id: json['id'],
      content: json['content'] ?? '',
      isRead: json['isRead'] ?? false,
    );
  }
}
